In [51]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [52]:
data = pd.read_csv("C:/Users/Gift Ukpoweh/Downloads/dirty_cafe_sales.csv")

data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [53]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [54]:
data.shape

(10000, 8)

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [56]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [57]:
data["Transaction Date"].value_counts()

UNKNOWN       159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-07-21     39
             ...
2023-04-27     15
2023-09-24     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: Transaction Date, Length: 367, dtype: int64

In [58]:
data["Transaction Date"] = data["Transaction Date"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [59]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [60]:
data = data.dropna(subset=["Transaction Date"])

In [61]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [62]:
data["Transaction Date"] = pd.to_datetime(data["Transaction Date"])

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9225 non-null   object
 2   Quantity          9405 non-null   object
 3   Price Per Unit    9375 non-null   object
 4   Total Spent       9383 non-null   object
 5   Payment Method    7101 non-null   object
 6   Location          6422 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 670.8+ KB

In [64]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [65]:
data["Item"].value_counts()

Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      329
ERROR        283
Name: Item, dtype: int64

In [66]:
data["Item"] = data["Item"].replace({"ERROR":"UNKNOWN"})

In [67]:
data["Item"].value_counts()

Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      612
Name: Item, dtype: int64

In [68]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [69]:
data["Item"] = data["Item"].fillna("UNKNOWN")

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9405 non-null   object
 3   Price Per Unit    9375 non-null   object
 4   Total Spent       9383 non-null   object
 5   Payment Method    7101 non-null   object
 6   Location          6422 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 670.8+ KB

In [71]:
data["Payment Method"].value_counts()

Digital Wallet    2197
Credit Card       2170
Cash              2158
ERROR              296
UNKNOWN            280
Name: Payment Method, dtype: int64

In [72]:
data["Payment Method"] = data["Payment Method"].replace({"ERROR":"UNKNOWN"})

In [73]:
data["Payment Method"].value_counts()

Digital Wallet    2197
Credit Card       2170
Cash              2158
UNKNOWN            576
Name: Payment Method, dtype: int64

In [74]:
data["Payment Method"] = data["Payment Method"].fillna("UNKNOWN")

In [75]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method         0
Location            3118
Transaction Date       0
dtype: int64

In [76]:
data["Location"].value_counts()

Takeaway    2889
In-store    2872
ERROR        341
UNKNOWN      320
Name: Location, dtype: int64

In [77]:
data["Location"] = data["Location"].replace({"ERROR":"UNKNOWN"})

In [78]:
data["Location"] = data["Location"].fillna("UNKNOWN")

In [79]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [80]:
data["Quantity"].value_counts()

5          1914
2          1892
4          1774
3          1766
1          1740
UNKNOWN     160
ERROR       159
Name: Quantity, dtype: int64

In [81]:
data["Quantity"] = data["Quantity"].replace({"UNKNOWN":0, "ERROR":0})
data["Price Per Unit"] = data["Price Per Unit"].replace({"UNKNOWN":0, "ERROR":0})
data["Total Spent"] = data["Total Spent"].replace({"UNKNOWN":0, "ERROR":0})

In [82]:
data["Quantity"] = pd.to_numeric(data["Quantity"], errors="coerce")
data["Price Per Unit"] = pd.to_numeric(data["Price Per Unit"], errors="coerce")
data["Total Spent"] = pd.to_numeric(data["Total Spent"], errors="coerce")

In [83]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9405 non-null   float64
 3   Price Per Unit    9375 non-null   float64
 4   Total Spent       9383 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 670.8+ KB

In [84]:
data["Quantity"] = data["Quantity"].fillna(data["Quantity"].mean())

In [85]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [86]:
data["Price Per Unit"] = data["Price Per Unit"].fillna(data["Price Per Unit"].mean())

In [87]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [88]:
data["Total Spent"] = data["Quantity"] * data["Price Per Unit"]

In [89]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [90]:
data.duplicated().sum()

0

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9540 non-null   float64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 670.8+ KB

In [92]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [93]:
data.to_csv("cleaned_cafe_sales.csv", index=False)